from sqlalchemy import Column, Integer, String, Boolean, ForeignKey, Float, DateTime, LargeBinary
from sqlalchemy.orm import relationship
from database import Base
import datetime

class User(Base):
    __tablename__ = "users"
    id = Column(Integer, primary_key=True, index=True)
    username = Column(String, unique=True, index=True)
    hashed_password = Column(String)
    email = Column(String, nullable=True)
    role = Column(String) # 'principal', 'admin', 'teacher', 'parent'
    student_id = Column(Integer, ForeignKey("students.id"), nullable=True) # Only for parents
    
    student = relationship("Student", back_populates="parent_user", foreign_keys=[student_id])

class ClassGroup(Base):
    __tablename__ = "classes"
    id = Column(Integer, primary_key=True, index=True)
    name = Column(String, unique=True, index=True) # e.g., 'Class 3'
    sections = relationship("Section", back_populates="class_group")



class Section(Base):
    __tablename__ = "sections"
    id = Column(Integer, primary_key=True, index=True)
    name = Column(String, index=True) # e.g., 'Section A'
    class_id = Column(Integer, ForeignKey("classes.id"))
    class_group = relationship("ClassGroup", back_populates="sections")
    students = relationship("Student", back_populates="section")


class Subject(Base):
    """Admin-managed, per-CLASS (not per-section — every section within the same class
    shares this list, since e.g. Class 3 Section A and Section B are taught the same
    subjects, but Class 3 and Class 8 are not). Replaces the old hardcoded dropdown
    (General/Mathematics/Science/History/English) that used to show on every school
    regardless of whether the admin had actually added anything."""
    __tablename__ = "subjects"
    id = Column(Integer, primary_key=True, index=True)
    class_id = Column(Integer, ForeignKey("classes.id"), index=True)
    name = Column(String, index=True)

class Student(Base):
    __tablename__ = "students"
    id = Column(Integer, primary_key=True, index=True)
    name = Column(String, index=True)
    roll_no = Column(String, unique=True, index=True)
    section_id = Column(Integer, ForeignKey("sections.id"))
    section = relationship("Section", back_populates="students")
    
    # Raw photo uploaded by parent — legacy DB blob (old students, kept for compat)
    image_data = Column(LargeBinary, nullable=True)
    # S3 object key for the same photo — new uploads go here instead of the DB
    photo_s3_key = Column(String, nullable=True)
    # Face embedding generated by admin (dimensionality depends on the engine)
    embedding_vector = Column(LargeBinary, nullable=True)
    # Which engine produced embedding_vector (e.g. 'dlib_resnet_v1') — only same-engine
    # vectors are ever matched against each other.
    embedding_model = Column(String, nullable=True)
    # True until the parent captures a live photo on first login
    parent_must_capture = Column(Boolean, default=True)
    # Soft delete: NULL = active/normal. Set instead of actually removing the row, so
    # attendance history stays intact for year-long reporting even after a student
    # leaves — "deleting" just hides them from active rosters/logins, reversibly.
    deleted_at = Column(DateTime, nullable=True)

    attendance_records = relationship("AttendanceRecord", back_populates="student")
    parent_user = relationship("User", back_populates="student", uselist=False, foreign_keys=[User.student_id])
    # Multiple reference embeddings (one per enrolled photo) — feeds the KNN gallery.
    embeddings = relationship("StudentEmbedding", back_populates="student",
                              cascade="all, delete-orphan")

class StudentEmbedding(Base):
    """One reference embedding per enrolled photo. Several rows per student so the
    KNN classifier can vote across multiple shots of the same person."""
    __tablename__ = "student_embeddings"
    id = Column(Integer, primary_key=True, index=True)
    student_id = Column(Integer, ForeignKey("students.id"), index=True)
    vector = Column(LargeBinary)              # float32 bytes
    embedding_model = Column(String)          # engine that produced it
    source = Column(String, nullable=True)    # original photo filename

    student = relationship("Student", back_populates="embeddings")

class AttendanceRecord(Base):
    __tablename__ = "attendance_records"
    id = Column(Integer, primary_key=True, index=True)
    student_id = Column(Integer, ForeignKey("students.id"))
    date = Column(DateTime, default=datetime.datetime.utcnow)
    status = Column(String) # 'present', 'absent', 'leave'
    subject = Column(String, default="General")
    
    student = relationship("Student", back_populates="attendance_records")

class Notification(Base):
    __tablename__ = "notifications"
    id = Column(Integer, primary_key=True, index=True)
    student_id = Column(Integer, ForeignKey("students.id"), index=True)
    message = Column(String)
    created_at = Column(DateTime, default=datetime.datetime.utcnow)
    is_read = Column(Boolean, default=False)

    student = relationship("Student")

class ParentChild(Base):
    """Additional parent-to-student links, beyond the legacy single User.student_id
    field — lets one parent account cover multiple children (e.g. siblings). The legacy
    field still works unchanged for single-child families; this table is only consulted
    when a parent has more than one child."""
    __tablename__ = "parent_children"
    id = Column(Integer, primary_key=True, index=True)
    parent_id = Column(Integer, ForeignKey("users.id"), index=True)
    student_id = Column(Integer, ForeignKey("students.id"), index=True)

    parent = relationship("User")
    student = relationship("Student")


class LeaveRequest(Base):
    __tablename__ = "leave_requests"
    id = Column(Integer, primary_key=True, index=True)
    student_id = Column(Integer, ForeignKey("students.id"))
    start_date = Column(DateTime)
    end_date = Column(DateTime)
    reason = Column(String)
    # Legacy single status — no longer written to by new code (kept only so old rows
    # still have a value). The real, authoritative decision now lives per-subject on
    # LeaveApproval below, since each subject's teacher decides independently.
    status = Column(String, default="pending") # 'pending', 'approved', 'rejected'

    student = relationship("Student")
    approvals = relationship("LeaveApproval", back_populates="leave_request", cascade="all, delete-orphan")


class LeaveApproval(Base):
    """One row per (leave_request, subject) — a single leave request (one date range,
    one reason) fans out into a separate approve/reject decision per subject taught in
    the student's section, since each subject's own teacher decides independently
    whether their class counts as excused for those days. A Hindi teacher approving a
    leave has no effect on the English teacher's own pending/approved/rejected decision
    for the same days. Created automatically (one row per subject in the student's
    section) when the parent submits the leave request."""
    __tablename__ = "leave_approvals"
    id = Column(Integer, primary_key=True, index=True)
    leave_request_id = Column(Integer, ForeignKey("leave_requests.id"), index=True)
    subject = Column(String, index=True)
    status = Column(String, default="pending")  # 'pending', 'approved', 'rejected'
    decided_by = Column(Integer, ForeignKey("users.id"), nullable=True)
    decided_at = Column(DateTime, nullable=True)

    leave_request = relationship("LeaveRequest", back_populates="approvals")
    decider = relationship("User")


class TeacherAssignment(Base):
    """Which (section, subject) pairs a teacher is assigned to teach — admin-managed.
    Once at least one assignment exists for a given (section_id, subject) pair, ONLY the
    teacher(s) assigned to it may take attendance / recognize photos / approve leave
    requests for that pair. A (section, subject) pair with NO assignment row at all
    falls back to "any teacher in the school may act on it" — the original, unrestricted
    behavior — so a school that hasn't set this up yet keeps working unchanged."""
    __tablename__ = "teacher_assignments"
    id = Column(Integer, primary_key=True, index=True)
    teacher_id = Column(Integer, ForeignKey("users.id"), index=True)
    section_id = Column(Integer, ForeignKey("sections.id"), index=True)
    subject = Column(String, index=True)

    teacher = relationship("User")
    section = relationship("Section")


class RecognitionThreshold(Base):
    """Auto-computed cosine match cutoffs, per section AND per student, per engine.

    Recomputed whenever a section's embedding gallery changes. NEVER global — each
    section (and each student within it) gets a cutoff fitted to its own genuine-vs-
    impostor score distribution, so a class where students look alike is gated more
    strictly than one where they don't.

    student_id NULL  -> the section-level baseline (fallback for students without
                        enough data or with overlapping genuine/impostor scores).
    student_id set   -> that student's own cutoff (may be above OR below the section
                        baseline; placed in the safe gap between their worst impostor
                        and their weakest genuine match).
    """
    __tablename__ = "recognition_thresholds"
    id = Column(Integer, primary_key=True, index=True)
    section_id = Column(Integer, ForeignKey("sections.id"), index=True)
    student_id = Column(Integer, ForeignKey("students.id"), nullable=True, index=True)
    embedding_model = Column(String, index=True)   # engine the cutoff was fitted for
    threshold = Column(Float)
    scope = Column(String)                          # 'section' | 'student'
    quality = Column(String, nullable=True)         # 'ok' | 'low_margin' | 'fallback'
    n_genuine = Column(Integer, default=0)
    n_impostor = Column(Integer, default=0)
    computed_at = Column(DateTime, default=datetime.datetime.utcnow)


class SuperAdminUser(Base):
    """Operator-level account (you) — manages school onboarding. Wholly separate from the
    per-school `User` table: a super admin doesn't belong to any school and never touches
    student/attendance data directly, so it's deliberately not just another User role."""
    __tablename__ = "super_admin_users"
    id = Column(Integer, primary_key=True, index=True)
    username = Column(String, unique=True, index=True)
    hashed_password = Column(String)


class School(Base):
    """One row per onboarded (or onboarding) school. Doubles as the onboarding-request
    record: `status` tracks the whole lifecycle from invite link creation through to a
    live, provisioned tenant, so there's one row per school throughout its entire history
    rather than a separate request table that gets reconciled into this one later.

    Secrets (Supabase connection string, our deploy private key, the school's runtime
    model-service API key) are stored via provisioning.encrypt_secret — never plaintext.
    """
    __tablename__ = "schools"
    id = Column(Integer, primary_key=True, index=True)
    name = Column(String, index=True)
    contact_email = Column(String, nullable=True)

    onboarding_token = Column(String, unique=True, index=True)
    # invited -> submitted -> (provisioning -> active) | failed
    #         -> rejected -> (back to submitted on resubmit)
    status = Column(String, default="invited")
    rejection_reason = Column(String, nullable=True)
    provisioning_error = Column(String, nullable=True)

    # Deploy keypair WE generate for this school — only the public half is ever shown to
    # them (paste into their EC2 instance's authorized_keys). The private half is ours,
    # encrypted at rest, and is the only credential we ever hold for their infrastructure.
    deploy_public_key = Column(String, nullable=True)
    deploy_private_key_encrypted = Column(String, nullable=True)

    elastic_ip = Column(String, nullable=True)
    supabase_db_url_encrypted = Column(String, nullable=True)

    model_service_api_key_encrypted = Column(String, nullable=True)

    # Whether the school's model service is currently stopped (suspended by the super
    # admin — e.g. non-payment) — independent of `status`, which tracks the onboarding
    # lifecycle rather than day-to-day service availability.
    service_stopped = Column(Boolean, default=False)

    # First admin account created in the school's own (tenant) database once provisioned.
    admin_username = Column(String, nullable=True)
    # Plaintext password, held ONLY until the onboarding page has displayed it once, then
    # cleared — same "shown once" convention as every other generated credential in this app.
    admin_password_plaintext = Column(String, nullable=True)

    created_at = Column(DateTime, default=datetime.datetime.utcnow)
    approved_at = Column(DateTime, nullable=True)


class S3Config(Base):
    """Lives in the SCHOOL's own tenant database (one row per school) — each school
    brings and manages their own S3 bucket for student photos, same ownership pattern
    as their EC2 server and Supabase database. Absence of a row (or of access_key)
    means this school hasn't set one up yet; photo storage then falls back to the
    legacy DB-blob path (Student.image_data), same as before this feature existed."""
    __tablename__ = "s3_config"
    id = Column(Integer, primary_key=True, index=True)
    access_key_encrypted = Column(String, nullable=True)
    secret_key_encrypted = Column(String, nullable=True)
    bucket_name = Column(String, nullable=True)
    region = Column(String, nullable=True)
    updated_at = Column(DateTime, default=datetime.datetime.utcnow, onupdate=datetime.datetime.utcnow)


class RecognitionSettings(Base):
    """Lives in the SCHOOL's own tenant database (one row per school) — how strict a
    match needs to be before a teacher's checklist auto-checks a student as present.
    Absence of a row (or a null threshold) means this school hasn't customized it yet;
    the app then falls back to the original hardcoded 0.90, unchanged from before this
    feature existed. Purely a UX convenience threshold — it does NOT touch the actual
    per-section/per-student cosine cutoffs in RecognitionThreshold, which stay
    auto-computed exactly as they always have."""
    __tablename__ = "recognition_settings"
    id = Column(Integer, primary_key=True, index=True)
    auto_check_threshold = Column(Float, nullable=True)
    updated_at = Column(DateTime, default=datetime.datetime.utcnow, onupdate=datetime.datetime.utcnow)


class SchoolEvent(Base):
    """Admin-managed announcement/event, shown on the parent dashboard's 'Upcoming
    Event' card — replaces what used to be a static placeholder there. Lives in the
    SCHOOL's own tenant database, same ownership pattern as classes/subjects."""
    __tablename__ = "school_events"
    id = Column(Integer, primary_key=True, index=True)
    title = Column(String)
    description = Column(String, nullable=True)
    event_date = Column(DateTime)
    created_at = Column(DateTime, default=datetime.datetime.utcnow)
